informal persian eliza
agp-internship/persian-eliza pull request #3
Opened 2022-08-01 18:57 UTC by masoumshaykhan

2022-08-05 19:37 UTC, soleyman79 requested changes

2022-08-05 19:37 UTC, soleyman79 commented on doctor.txt
> +    reasmb: میخوای که من رو (2)؟
اعداد به همراه پرانتز باید از دو طرف جدا از بقیه متن باشند. در غیر این صورت به شکل متن عادی پردازش شده و به درستی جایگزین نمی شوند. بنابراین در این خط (و چند خط دیگر) باید عبارت (2) ؟ جایگزین (2)؟ شود.

2022-08-05 19:37 UTC, soleyman79 commented on doctor.txt
> +    reasmb: واقعا، (2)؟
اینجا هم همان مشکل قبلی وجود دارد.

![image](https://user-images.githubusercontent.com/59196723/183148405-04909473-578f-4cfe-85cd-dd5539b7afe6.png)

2022-08-06 03:53 UTC, sadrasabouri commented
@soleyman79 Thanks for your review.
@masoumshaykhan Please either solve these issues or provide push access for @soleyman79 to your repository in order to solve these tiny problems.

2022-08-20 10:10 UTC, sadrasabouri approved these changes
Good job!

2022-08-20 10:12 UTC, merged